export const tasks: string[] = [
  "Practice deep breathing",
  "Write down three things you're grateful for",
  "Go for a 15-minute walk",
  "Create a positive affirmation and repeat it",
  "Try a 5-minute mindfulness meditation",
  "Reach out to a friend for a chat",
  "Read a chapter of a book you enjoy",
  "Engage in a creative hobby for 20 minutes",
  "Listen to your favorite uplifting song",
  "Keep a journal and jot down your thoughts",
  "Do a random act of kindness",
  "Declutter a small area of your space",
  "Watch a funny video or show",
  "Plan a future weekend getaway",
  "Do a quick body stretch",
  "Try a new healthy recipe",
  "Write a letter to your future self",
  "Practice gratitude journaling",
  "Watch the sunrise or sunset",
  "Create a vision board for your goals",
  "Learn a new word and use it",
  "Do a digital detox for an hour",
  "Do 10 minutes of guided self-reflection",
  "Visit a local park and people-watch",
  "Write down your strengths and accomplishments",
  "Dance to your favorite music for a break",
  "Practice a 10-minute yoga routine",
  "Watch motivational TED talks",
  "Try a new type of tea and savor it",
  "Set a small achievable goal for the day",
  "Do a puzzle or brain-teaser",
  "Volunteer for a cause you care about",
  "Take a power nap if you're tired",
  "Disconnect from social media for a while",
  "Paint, draw, or color in a coloring book",
  "Try a new type of exercise or sport",
  "Write a letter to someone you admire",
  "Plant a small indoor herb garden",
  "Practice progressive muscle relaxation",
  "Watch the clouds and find shapes",
  "Create a playlist of soothing music",
  "Learn to say 'no' without guilt",
  "Practice forgiveness, starting with yourself",
  "Do a digital declutter and organize files",
  "Cook a meal from a different culture",
  "Visit a museum or art gallery online",
  "Write down your worries and let them go",
  "Set a timer for a 5-minute dance party",
  "Make a list of your favorite quotes",
  "Spend time with a furry friend",
  "Try aromatherapy with calming scents",
  "Practice the 3-2-1 grounding technique",
  "Do a DIY project you've been postponing",
  "Explore a nearby nature trail",
  "Engage in a 20-minute mindfulness walk",
  "Create a self-care corner in your home",
  "Practice positive self-talk",
  "Watch a documentary on a topic of interest",
  "Create a playlist of motivational speeches",
  "Learn a new dance routine online",
  "Write a short story or poem",
  "Practice mindful eating with a snack",
  "Try a laughter yoga session",
  "Write down things you love about yourself",
  "Arrange a virtual coffee date with a friend",
  "Practice the 5-4-3-2-1 sensory grounding exercise",
  "Create a schedule for better time management",
  "Visit a virtual art exhibition",
  "Do a brain dump to clear your thoughts",
  "Write a thank-you note to someone",
  "Try a body scan meditation",
  "Practice the 'STOP' technique when stressed",
  "Engage in a 10-minute stretching routine",
  "Revisit an old hobby you used to enjoy",
  "Spend time in nature, even if it's brief",
  "Practice self-compassion in challenging moments",
  "Watch a motivational movie",
  "Create a list of future goals",
  "Visualize your ideal peaceful place",
  "Take breaks during work or study",
  "Try a virtual cooking class",
  "Practice positive visualization",
  "Explore a new podcast on well-being",
  "Create a self-love mantra",
  "Try a bodyweight workout routine",
  "Write a letter to release past regrets",
  "Practice mindful breathing for 3 minutes",
  "Watch the stars and identify constellations",
  "Reflect on your proudest achievements",
  "Visit a virtual zoo or aquarium",
  "Try a guided gratitude meditation",
  "Create a playlist of calming sounds",
  "Plan a picnic or outdoor meal",
  "Practice the '3 Good Things' exercise",
  "Listen to a motivational podcast",
  "Practice setting healthy boundaries",
  "Try a DIY skincare or relaxation routine",
  "Engage in a mindful coloring session",
  "Reflect on moments of personal growth",
  "Celebrate your progress and victories",
];
